"""migration

Revision ID: 0933db52205d
Revises: 2d049f93aab2
Create Date: 2025-09-08 02:19:42.969616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0933db52205d'
down_revision: Union[str, None] = '2d049f93aab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit_conversions', sa.Column('is_volume', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit_conversions', 'is_volume')
    # ### end Alembic commands ###
