"""migration

Revision ID: 1b88b2a304f0
Revises: f00cb6cc9dff
Create Date: 2025-11-15 21:36:14.737462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1b88b2a304f0'
down_revision: Union[str, None] = 'f00cb6cc9dff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_blocks')
    op.drop_table('articles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), nullable=True),
    sa.Column('namespace', sa.VARCHAR(length=255), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('extension', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('article_blocks',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('page_id', sa.INTEGER(), nullable=True),
    sa.Column('parent', sa.INTEGER(), nullable=True),
    sa.Column('kind', sa.VARCHAR(length=25), nullable=True),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.Column('extension', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['articles._id'], ),
    sa.ForeignKeyConstraint(['parent'], ['article_blocks._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###
