"""migration

Revision ID: 23a6f72e1c35
Revises: 78db563c16a3
Create Date: 2025-10-12 12:42:28.833541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23a6f72e1c35'
down_revision: Union[str, None] = '78db563c16a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient_compositions', sa.Column('daily_value', sa.Float(), nullable=True))
    op.drop_column('ingredient_compositions', 'daily_vlaue')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient_compositions', sa.Column('daily_vlaue', sa.FLOAT(), nullable=True))
    op.drop_column('ingredient_compositions', 'daily_value')
    # ### end Alembic commands ###
