"""migration

Revision ID: 28fb96248329
Revises: ea3d201cc8d7
Create Date: 2025-09-02 14:01:25.523721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28fb96248329'
down_revision: Union[str, None] = 'ea3d201cc8d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_value_store',
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('topic', 'key')
    )
    op.create_index('idx_keyvalue_key', 'key_value_store', ['key'], unique=False)
    op.create_index('idx_keyvalue_topic', 'key_value_store', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_keyvalue_topic', table_name='key_value_store')
    op.drop_index('idx_keyvalue_key', table_name='key_value_store')
    op.drop_table('key_value_store')
    # ### end Alembic commands ###
