"""migration

Revision ID: 2c77775efd98
Revises: d5e77a1c6d9d
Create Date: 2025-10-12 12:51:34.049019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c77775efd98'
down_revision: Union[str, None] = 'd5e77a1c6d9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient_compositions', sa.Column('kind', sa.String(length=50), nullable=True))
    op.drop_column('ingredient_compositions', 'subname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient_compositions', sa.Column('subname', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('ingredient_compositions', 'kind')
    # ### end Alembic commands ###
