"""migration

Revision ID: 2d049f93aab2
Revises: 5ea0a6cf9e8d
Create Date: 2025-09-06 21:05:37.614496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d049f93aab2'
down_revision: Union[str, None] = '5ea0a6cf9e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('count', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('ingredient', sa.String(length=50), nullable=True))
    op.add_column('recipe_ingredients', sa.Column('product', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_ingredients', 'product')
    op.drop_column('products', 'ingredient')
    op.drop_column('products', 'count')
    # ### end Alembic commands ###
