"""makefile

Revision ID: 416a585bbe05
Revises: cfe90d19e129
Create Date: 2025-06-25 09:15:25.473645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '416a585bbe05'
down_revision: Union[str, None] = 'cfe90d19e129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient_compositions')
    op.add_column('ingredients', sa.Column('composition', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'composition')
    op.create_table('ingredient_compositions',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('ingredient_id', sa.INTEGER(), nullable=True),
    sa.Column('composition', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###
