"""Add Tasks

Revision ID: 5420a441e29f
Revises: 6129d1f04ee4
Create Date: 2025-07-27 14:49:35.733962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5420a441e29f'
down_revision: Union[str, None] = '6129d1f04ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('datetime_start', sa.DateTime(), nullable=False),
    sa.Column('datetime_end', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('guests', sa.JSON(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('price_budget', sa.Float(), nullable=True),
    sa.Column('price_real', sa.Float(), nullable=True),
    sa.Column('people_count', sa.Integer(), nullable=True),
    sa.Column('template', sa.Boolean(), nullable=True),
    sa.Column('recuring', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('extension', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('tasks',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('datetime_deadline', sa.DateTime(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('price_budget', sa.Float(), nullable=True),
    sa.Column('price_real', sa.Float(), nullable=True),
    sa.Column('people_count', sa.Integer(), nullable=True),
    sa.Column('template', sa.Boolean(), nullable=True),
    sa.Column('recuring', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('extension', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('substasks',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['tasks._id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['tasks._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('substasks')
    op.drop_table('tasks')
    op.drop_table('events')
    # ### end Alembic commands ###
