"""migration

Revision ID: 555a85c7532b
Revises: 99b4ddf4b6b5
Create Date: 2025-08-10 21:17:46.940565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '555a85c7532b'
down_revision: Union[str, None] = '99b4ddf4b6b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_foreign_key(None, 'events', 'tasks', ['task'], ['_id'])
    except:
        pass
        
    op.add_column('ingredients', sa.Column('price_high', sa.Float(), nullable=True))
    op.add_column('ingredients', sa.Column('price_low', sa.Float(), nullable=True))
    op.add_column('ingredients', sa.Column('price_medium', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'price_medium')
    op.drop_column('ingredients', 'price_low')
    op.drop_column('ingredients', 'price_high')
    op.drop_constraint(None, 'events', type_='foreignkey')
    # ### end Alembic commands ###
