"""migration

Revision ID: 6524858f48d0
Revises: 9dd32a09b78f
Create Date: 2025-10-12 13:06:37.730145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6524858f48d0'
down_revision: Union[str, None] = '9dd32a09b78f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('ingredient_compositions', 'quantity',
    #            existing_type=sa.FLOAT(),
    #            nullable=True)
    # op.alter_column('ingredient_compositions', 'unit',
    #            existing_type=sa.VARCHAR(length=50),
    #            nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredient_compositions', 'unit',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('ingredient_compositions', 'quantity',
               existing_type=sa.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
