"""migration

Revision ID: 6582a1f54256
Revises: 0933db52205d
Create Date: 2025-09-09 21:43:25.512723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6582a1f54256'
down_revision: Union[str, None] = '0933db52205d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('unit_metric', sa.String(length=50), nullable=True))
    op.add_column('ingredients', sa.Column('unit_us_customary', sa.String(length=50), nullable=True))
    op.add_column('ingredients', sa.Column('unit_us_legal', sa.String(length=50), nullable=True))
    op.add_column('ingredients', sa.Column('unit_canada', sa.String(length=50), nullable=True))
    op.add_column('ingredients', sa.Column('unit_australia', sa.String(length=50), nullable=True))
    op.add_column('ingredients', sa.Column('unit_uk', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'unit_uk')
    op.drop_column('ingredients', 'unit_australia')
    op.drop_column('ingredients', 'unit_canada')
    op.drop_column('ingredients', 'unit_us_legal')
    op.drop_column('ingredients', 'unit_us_customary')
    op.drop_column('ingredients', 'unit_metric')
    # ### end Alembic commands ###
