"""makefile

Revision ID: 76253d4958e7
Revises: 416a585bbe05
Create Date: 2025-07-09 17:05:04.117790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '76253d4958e7'
down_revision: Union[str, None] = '416a585bbe05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nutrients')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrients',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('extension', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
