"""migration

Revision ID: 78db563c16a3
Revises: db3ae78efc22
Create Date: 2025-10-12 12:41:55.221420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78db563c16a3'
down_revision: Union[str, None] = 'db3ae78efc22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient_compositions', sa.Column('daily_vlaue', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient_compositions', 'daily_vlaue')
    # ### end Alembic commands ###
