"""migration

Revision ID: 94a12184c2b2
Revises: cc9776ca9629
Create Date: 2025-10-12 17:55:26.227335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '94a12184c2b2'
down_revision: Union[str, None] = 'cc9776ca9629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_compositions')
    op.add_column('ingredient_compositions', sa.Column('source', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient_compositions', 'source')
    op.create_table('recipe_compositions',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), nullable=False),
    sa.Column('kind', sa.VARCHAR(length=50), nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('unit', sa.VARCHAR(length=50), nullable=True),
    sa.Column('daily_value', sa.FLOAT(), nullable=True),
    sa.Column('extension', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###
