"""migration

Revision ID: 99b4ddf4b6b5
Revises: 5420a441e29f
Create Date: 2025-08-08 14:29:48.137352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99b4ddf4b6b5'
down_revision: Union[str, None] = '5420a441e29f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('task', sa.Integer(), nullable=True))
    try:
        op.create_foreign_key(None, 'events', 'tasks', ['task'], ['_id'])
    except:
        pass

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'task')
    # ### end Alembic commands ###
