"""migration

Revision ID: a553cd3e88eb
Revises: 6582a1f54256
Create Date: 2025-09-27 22:23:57.203342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a553cd3e88eb'
down_revision: Union[str, None] = '6582a1f54256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('component', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'component')
    # ### end Alembic commands ###
