"""migration

Revision ID: aa627281979b
Revises: a553cd3e88eb
Create Date: 2025-09-27 22:25:51.340173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa627281979b'
down_revision: Union[str, None] = 'a553cd3e88eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("foreign_recipe_key_id", 'recipes', ['recipe_id'], ['_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_constraint("foreign_recipe_key_id", type_='foreignkey')
        batch_op.drop_column('recipe_id')
    # ### end Alembic commands ###
