"""migration

Revision ID: b9f77156bde5
Revises: d7b0235342e1
Create Date: 2025-11-01 19:32:02.907355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9f77156bde5'
down_revision: Union[str, None] = 'd7b0235342e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('owner', sa.String(length=200), nullable=True))
    op.add_column('events', sa.Column('name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'name')
    op.drop_column('events', 'owner')
    # ### end Alembic commands ###
