"""migration

Revision ID: bec2ddf0888d
Revises: 403343989ff7
Create Date: 2026-04-06 16:40:37.549900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bec2ddf0888d'
down_revision: Union[str, None] = '403343989ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('public', sa.Boolean(), nullable=True))
    op.add_column('articles', sa.Column('article_kind', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'article_kind')
    op.drop_column('articles', 'public')
    # ### end Alembic commands ###
