"""migration

Revision ID: d5e77a1c6d9d
Revises: 23a6f72e1c35
Create Date: 2025-10-12 12:46:11.908896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e77a1c6d9d'
down_revision: Union[str, None] = '23a6f72e1c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient_compositions', sa.Column('subname', sa.String(length=50), nullable=True))
    op.drop_column('ingredient_compositions', 'kind')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient_compositions', sa.Column('kind', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('ingredient_compositions', 'subname')
    # ### end Alembic commands ###
