"""migration

Revision ID: d7b0235342e1
Revises: dc5e336a51f6
Create Date: 2025-10-14 19:09:34.919219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7b0235342e1'
down_revision: Union[str, None] = 'dc5e336a51f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient_compositions', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('recipe_id_foreign_const'), type_='foreignkey')
        batch_op.create_foreign_key('recipe_id_foreign_const', 'recipes', ['recipe_id'], ['_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredient_compositions', type_='foreignkey')
    op.create_foreign_key(op.f('recipe_id_foreign_const'), 'ingredient_compositions', 'ingredients', ['recipe_id'], ['_id'])
    # ### end Alembic commands ###
