"""migration

Revision ID: db3ae78efc22
Revises: e04a8f4adeb7
Create Date: 2025-10-12 12:33:22.243739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'db3ae78efc22'
down_revision: Union[str, None] = 'e04a8f4adeb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('composed_recipe_recipes')
    op.drop_table('composed')
    op.add_column('ingredient_compositions', sa.Column('kind', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient_compositions', 'kind')
    op.create_table('composed',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('images', sqlite.JSON(), nullable=True),
    sa.Column('prep_time', sa.INTEGER(), nullable=True),
    sa.Column('cook_time', sa.INTEGER(), nullable=True),
    sa.Column('servings', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('author_id', sa.INTEGER(), nullable=True),
    sa.Column('extension', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('composed_recipe_recipes',
    sa.Column('composed_recipe_id', sa.INTEGER(), nullable=True),
    sa.Column('recipe_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['composed_recipe_id'], ['composed._id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes._id'], )
    )
    # ### end Alembic commands ###
