"""migration

Revision ID: dc5e336a51f6
Revises: 94a12184c2b2
Create Date: 2025-10-14 19:02:47.084645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc5e336a51f6'
down_revision: Union[str, None] = '94a12184c2b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient_compositions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id', sa.Integer(), nullable=True))
        batch_op.alter_column('ingredient_id',
                existing_type=sa.INTEGER(),
                nullable=True)
        batch_op.create_foreign_key('recipe_id_foreign_const', 'ingredients', ['recipe_id'], ['_id'])

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fdc_id', sa.Integer(), nullable=True))
    
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fdc_id', sa.Integer(), nullable=True))
    
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fdc_id', sa.Integer(), nullable=True))
        # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_ingredients', 'fdc_id')
    op.drop_column('products', 'fdc_id')
    op.drop_column('ingredients', 'fdc_id')
    op.drop_constraint(None, 'ingredient_compositions', type_='foreignkey')
    op.alter_column('ingredient_compositions', 'ingredient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('ingredient_compositions', 'recipe_id')
    # ### end Alembic commands ###
