"""migration

Revision ID: dd890e5b365c
Revises: 1c4fbf2c41d3
Create Date: 2025-12-27 18:35:46.128152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd890e5b365c'
down_revision: Union[str, None] = '1c4fbf2c41d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_blocks', sa.Column('sequence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_blocks', 'sequence')
    # ### end Alembic commands ###
