"""migration

Revision ID: e04a8f4adeb7
Revises: aa627281979b
Create Date: 2025-09-28 00:44:09.460765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e04a8f4adeb7'
down_revision: Union[str, None] = 'aa627281979b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('foreign_recipe_key_id'), type_='foreignkey')
        batch_op.drop_column('recipe_id')

    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredient_recipe_id', sa.Integer(), nullable=True))
        batch_op.alter_column('ingredient_id',
                existing_type=sa.INTEGER(),
                nullable=True)
        batch_op.create_foreign_key('foreign_key_ingredient_recipe', 'recipes', ['ingredient_recipe_id'], ['_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe_ingredients', type_='foreignkey')
    op.alter_column('recipe_ingredients', 'ingredient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('recipe_ingredients', 'ingredient_recipe_id')
    op.add_column('ingredients', sa.Column('recipe_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(op.f('foreign_recipe_key_id'), 'ingredients', 'recipes', ['recipe_id'], ['_id'])
    # ### end Alembic commands ###
