"""migration

Revision ID: ea3d201cc8d7
Revises: ca065bbd5a31
Create Date: 2025-09-02 13:35:58.195252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea3d201cc8d7'
down_revision: Union[str, None] = 'ca065bbd5a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_keyvalue_key', 'key_value_store', ['key'], unique=False)
    op.create_index('idx_keyvalue_topic', 'key_value_store', ['topic'], unique=False)
    op.drop_column('key_value_store', '_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key_value_store', sa.Column('_id', sa.INTEGER(), nullable=False))
    op.drop_index('idx_keyvalue_topic', table_name='key_value_store')
    op.drop_index('idx_keyvalue_key', table_name='key_value_store')
    # ### end Alembic commands ###
